name: 4D-humans
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pytorch==2.4.0
  - pytorch-cuda=12.4
  - torchvision==0.19.0
  - pip
  - pip:
      - pytorch-lightning
      - smplx==0.1.28
      - pyrender
      - opencv-python
      - yacs
      - scikit-image
      - einops
      - timm
      - dill
      - pandas
      - git+https://github.com/hansen1416/detectron2.git@a59f05630a8f205756064244bf5beb8661f96180
      - git+https://github.com/mattloper/chumpy

      # For training
      - rich
      - hydra-core
      - hydra-submitit-launcher
      - hydra-colorlog
      - pyrootutils
      - webdataset

      # for pyrender
      # apt-get install libosmesa6-dev freeglut3-dev
